-- ============================================================
-- Migration 5: 듀오링고 단어 대량 추가 (스페인어 282개, 중국어 823개)
-- 스페인어는 단어장 1개, 중국어는 듀오링고 유닛별로 단어장 41개 생성
-- ============================================================
do $$
declare
  v_owner uuid;
  v_deck uuid;
begin
  select owner_id into v_owner from public.decks order by created_at limit 1;
  if v_owner is null then
    raise exception '단어장 소유자를 찾을 수 없습니다. 기존 단어장이 최소 1개 있어야 합니다.';
  end if;

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '듀오링고 스페인어 단어장', '🦉', '스페인어') returning id into v_deck;
  insert into public.words (deck_id, front, back) values
    (v_deck, 'maría', '마리아(이름)'),
    (v_deck, 'pablo', '파블로(이름)'),
    (v_deck, 'jugo', '주스'),
    (v_deck, 'bienvenido', '환영합니다'),
    (v_deck, 'buenos días', '좋은 아침'),
    (v_deck, 'yo soy', '나는 ~이다'),
    (v_deck, 'luis', '루이스(이름)'),
    (v_deck, 'mucho gusto', '만나서 반갑습니다'),
    (v_deck, 'él es', '그는 ~이다'),
    (v_deck, 'mi mejor amigo', '나의 가장 친한 친구'),
    (v_deck, 'bien', '잘, 좋게'),
    (v_deck, 'qué', '무엇'),
    (v_deck, 'hasta luego', '또 봐요'),
    (v_deck, 'ana', '아나(이름)'),
    (v_deck, 'ella', '그녀'),
    (v_deck, 'alemania', '독일 (원문 오타 "almenia" 수정함)'),
    (v_deck, 'méxico', '멕시코'),
    (v_deck, 'buenas tardes', '안녕하세요(오후 인사)'),
    (v_deck, 'de dónde eres', '어디에서 왔어?'),
    (v_deck, 'encantado', '만나서 반갑습니다(남성형)'),
    (v_deck, 'francia', '프랑스'),
    (v_deck, 'sí', '네'),
    (v_deck, 'tú', '너'),
    (v_deck, 'verdad', '사실, ~그렇지?(부가의문)'),
    (v_deck, 'mamá', '엄마'),
    (v_deck, 'no', '아니요'),
    (v_deck, 'diego', '디에고(이름)'),
    (v_deck, 'mi', '나의'),
    (v_deck, 'compañero de cuarto', '룸메이트'),
    (v_deck, 'uno', '하나(숫자 1)'),
    (v_deck, 'tengo', '나는 가지고 있다'),
    (v_deck, 'quiere', '그/그녀는 원한다'),
    (v_deck, 'hermano', '형제(형/오빠/남동생)'),
    (v_deck, 'hermana', '자매(언니/누나/여동생)'),
    (v_deck, 'hijo', '아들'),
    (v_deck, 'hija', '딸'),
    (v_deck, 'en realidad', '사실은'),
    (v_deck, 'solamente', '오직'),
    (v_deck, 'una', '하나(여성형)'),
    (v_deck, 'pedro', '페드로(이름)'),
    (v_deck, 'tío', '삼촌'),
    (v_deck, 'tía', '이모/고모'),
    (v_deck, 'amigo', '친구'),
    (v_deck, 'compañero de trabajo', '직장 동료'),
    (v_deck, 'laura', '라우라(이름)'),
    (v_deck, 'también', '또한'),
    (v_deck, 'esposo', '남편'),
    (v_deck, 'abuelo', '할아버지'),
    (v_deck, 'abuela', '할머니'),
    (v_deck, 'como yo', '나처럼'),
    (v_deck, 'tímido', '수줍은'),
    (v_deck, 'no crees', '그렇게 생각 안 해?'),
    (v_deck, 'simpático', '친절한, 호감 가는'),
    (v_deck, 'creo que', '나는 ~라고 생각해'),
    (v_deck, 'novio', '남자친구'),
    (v_deck, 'novia', '여자친구'),
    (v_deck, 'cómo es tu', '너의 ~는 어때?'),
    (v_deck, 'gracioso', '재미있는, 웃긴'),
    (v_deck, 'papá', '아빠'),
    (v_deck, 'serio', '진지한'),
    (v_deck, 'pero', '하지만'),
    (v_deck, 'maleta', '여행가방'),
    (v_deck, 'pasaporte', '여권'),
    (v_deck, 'tranquilo', '차분한'),
    (v_deck, 'tengo', '나는 가지고 있다'),
    (v_deck, 'está aquí', '여기 있다'),
    (v_deck, 'cartera', '지갑'),
    (v_deck, 'vestido', '드레스'),
    (v_deck, 'suéter', '스웨터'),
    (v_deck, 'chaqueta', '재킷'),
    (v_deck, 'dónde', '어디'),
    (v_deck, 'reloj', '시계'),
    (v_deck, 'gorra', '모자'),
    (v_deck, 'cargador', '충전기'),
    (v_deck, 'ay', '아이고!(감탄사)'),
    (v_deck, 'nuevo', '새로운'),
    (v_deck, 'no encuentro', '못 찾겠어'),
    (v_deck, 'mochila', '백팩'),
    (v_deck, 'dónde está ~', '는 어디에 있어?'),
    (v_deck, 'libro', '책'),
    (v_deck, 'tableta', '태블릿'),
    (v_deck, 'pues', '음..., 그러니까'),
    (v_deck, 'no', '아니요'),
    (v_deck, 'lucía', '루시아(이름)'),
    (v_deck, 'panadería', '빵집'),
    (v_deck, 'hay ~', '이 있다'),
    (v_deck, 'cafetería', '카페'),
    (v_deck, 'por aquí', '이쪽으로'),
    (v_deck, 'tienda', '가게'),
    (v_deck, 'teatro', '극장'),
    (v_deck, 'banco', '은행'),
    (v_deck, 'museo', '박물관'),
    (v_deck, 'cerca', '가까운'),
    (v_deck, 'estación de metro', '지하철역'),
    (v_deck, 'centro comercial', '쇼핑몰'),
    (v_deck, 'parque', '공원'),
    (v_deck, 'oye', '저기, 있잖아'),
    (v_deck, 'en ~', '에서'),
    (v_deck, 'barrio', '동네'),
    (v_deck, 'ciudad', '도시'),
    (v_deck, 'librería', '서점'),
    (v_deck, 'hotel', '호텔'),
    (v_deck, 'no hay', '없다'),
    (v_deck, 'mira', '봐'),
    (v_deck, 'pueblo', '마을'),
    (v_deck, 'estacionamiento', '주차장'),
    (v_deck, 'español', '스페인어'),
    (v_deck, 'portugués', '포르투갈어'),
    (v_deck, 'y tú', '너는?'),
    (v_deck, 'escuela', '학교'),
    (v_deck, 'estudio', '나는 공부한다'),
    (v_deck, 'estudias', '너는 공부한다'),
    (v_deck, 'inglés', '영어'),
    (v_deck, 'francés', '프랑스어'),
    (v_deck, 'genial', '멋지다, 좋다'),
    (v_deck, 'hablo', '나는 말한다'),
    (v_deck, 'hablas', '너는 말한다'),
    (v_deck, 'un poco de', '약간의'),
    (v_deck, 'muy bien', '아주 잘'),
    (v_deck, 'italiano', '이탈리아어'),
    (v_deck, 'alemán', '독일어'),
    (v_deck, 'guau', '와(감탄사)'),
    (v_deck, 'por la mañana', '아침에'),
    (v_deck, 'casa', '집'),
    (v_deck, 'música', '음악'),
    (v_deck, 'arte', '예술'),
    (v_deck, 'por la noche', '밤에'),
    (v_deck, 'frío', '추운, 추위'),
    (v_deck, 'abrigo', '외투'),
    (v_deck, 'uso', '나는 사용한다'),
    (v_deck, 'en ~', '에'),
    (v_deck, 'otoño', '가을'),
    (v_deck, 'hace (', '날씨가) ~하다'),
    (v_deck, 'viento', '바람'),
    (v_deck, 'calor', '더위'),
    (v_deck, 'verano', '여름'),
    (v_deck, 'enero 1', '월'),
    (v_deck, 'ahora', '지금'),
    (v_deck, 'julio 7', '월'),
    (v_deck, 'traje de baño', '수영복'),
    (v_deck, 'hoy', '오늘'),
    (v_deck, 'marzo 3', '월'),
    (v_deck, 'país', '나라'),
    (v_deck, 'septiembre 9', '월'),
    (v_deck, 'primavera', '봄'),
    (v_deck, 'invierno', '겨울'),
    (v_deck, 'buen tiempo', '좋은 날씨'),
    (v_deck, 'mucho', '많이'),
    (v_deck, 'allí', '저기'),
    (v_deck, 'octubre 10', '월'),
    (v_deck, 'diciembre 12', '월'),
    (v_deck, 'sol', '태양'),
    (v_deck, 'piña', '파인애플'),
    (v_deck, 'sandía', '수박'),
    (v_deck, 'bolsa', '봉지, 가방'),
    (v_deck, 'mercado', '시장'),
    (v_deck, 'necesito', '나는 필요하다'),
    (v_deck, 'necesitas', '너는 필요하다'),
    (v_deck, 'durazno', '복숭아'),
    (v_deck, 'cuánto cuesta', '얼마예요(단수)'),
    (v_deck, 'cuánto cuestan', '얼마예요(복수)'),
    (v_deck, 'dos', '둘'),
    (v_deck, 'más', '더'),
    (v_deck, 'botella de ~', '한 병'),
    (v_deck, 'mango', '망고'),
    (v_deck, 'naranja', '오렌지'),
    (v_deck, 'tres', '셋'),
    (v_deck, 'kilo', '킬로(그램)'),
    (v_deck, 'este', '이것'),
    (v_deck, 'edificio', '건물'),
    (v_deck, 'vivo', '나는 산다'),
    (v_deck, 'apartamento', '아파트'),
    (v_deck, 'lejos', '먼'),
    (v_deck, 'pequeño', '작은'),
    (v_deck, 'piso', '층, 집(스페인식 아파트)'),
    (v_deck, 'perro', '개'),
    (v_deck, 'gato', '고양이'),
    (v_deck, 'familia', '가족'),
    (v_deck, 'solo', '혼자'),
    (v_deck, 'con ~', '와 함께'),
    (v_deck, 'pareja', '커플, 애인'),
    (v_deck, 'jardín', '정원'),
    (v_deck, 'terraza', '테라스'),
    (v_deck, 'grande', '큰'),
    (v_deck, 'bonito', '예쁜'),
    (v_deck, 'garaje', '차고'),
    (v_deck, 'muy', '매우'),
    (v_deck, 'tiene', '그/그녀는 가지고 있다'),
    (v_deck, 'calle', '거리'),
    (v_deck, 'restaurante', '식당'),
    (v_deck, 'tranquilo', '조용한'),
    (v_deck, 'supermercado', '슈퍼마켓'),
    (v_deck, 'parque', '공원'),
    (v_deck, 'me gusta', '나는 좋아한다'),
    (v_deck, 'muchos', '많은'),
    (v_deck, 'es divertido', '재미있다'),
    (v_deck, 'tiempo libre', '자유시간, 여가'),
    (v_deck, 'bailo', '나는 춤춘다'),
    (v_deck, 'bailas', '너는 춤춘다'),
    (v_deck, 'canto', '나는 노래한다'),
    (v_deck, 'cantar', '노래하다(동사원형)'),
    (v_deck, 'cantan', '그들은 노래한다'),
    (v_deck, 'salsa', '살사(춤/음악)'),
    (v_deck, 'escucha', '듣다(그/그녀는 듣는다, 또는 명령형 "들어봐")'),
    (v_deck, 'discoteca', '클럽, 디스코텍'),
    (v_deck, 'ustedes', '당신들(복수)'),
    (v_deck, 'qué haces', '뭐 해?'),
    (v_deck, 'miro películas', '나는 영화를 본다'),
    (v_deck, 'viajas', '너는 여행한다'),
    (v_deck, 'viajo', '나는 여행한다'),
    (v_deck, 'viajan', '그들은 여행한다'),
    (v_deck, 'mucho', '많이'),
    (v_deck, 'en tren', '기차로'),
    (v_deck, 'en coche', '차로'),
    (v_deck, 'bueno', '좋아, 그래'),
    (v_deck, 'pintas', '너는 그림 그린다'),
    (v_deck, 'nosotros', '우리(남성)'),
    (v_deck, 'nosotras', '우리(여성)'),
    (v_deck, 'su', '그의/그녀의/그들의'),
    (v_deck, 'somos', '우리는 ~이다'),
    (v_deck, 'hermanas', '자매들'),
    (v_deck, 'arroz', '쌀, 밥'),
    (v_deck, 'sopa', '수프'),
    (v_deck, 'pasta', '파스타'),
    (v_deck, 'con pollo', '닭고기를 곁들인'),
    (v_deck, 'cocino', '나는 요리한다'),
    (v_deck, 'cocinamos', '우리는 요리한다'),
    (v_deck, 'gimnasio', '헬스장'),
    (v_deck, 'fútbol', '축구'),
    (v_deck, 'practico', '나는 연습한다'),
    (v_deck, 'entrena', '그/그녀는 훈련한다'),
    (v_deck, 'frecuentemente', '자주'),
    (v_deck, 'al aire libre', '야외에서'),
    (v_deck, 'piscina', '수영장'),
    (v_deck, 'nado', '나는 수영한다'),
    (v_deck, 'tenis', '테니스'),
    (v_deck, 'todos los días', '매일'),
    (v_deck, 'levanto pesas', '나는 웨이트를 든다'),
    (v_deck, 'equipo', '팀, 장비'),
    (v_deck, 'básquetbol', '농구'),
    (v_deck, 'ellas', '그녀들'),
    (v_deck, 'a menudo', '자주'),
    (v_deck, 'esquío', '나는 스키를 탄다'),
    (v_deck, 'ya no', '더 이상 ~않다'),
    (v_deck, 'ah', '아(감탄사)'),
    (v_deck, 'beísbol', '야구'),
    (v_deck, 'ellos', '그들'),
    (v_deck, 'perezoso', '게으른'),
    (v_deck, 'entrenador', '코치, 트레이너'),
    (v_deck, 'honestamente', '솔직히'),
    (v_deck, 'siempre', '항상'),
    (v_deck, 'caminas', '너는 걷는다'),
    (v_deck, 'descanso', '나는 쉰다, 휴식'),
    (v_deck, 'atlético', '운동을 잘하는'),
    (v_deck, 'porque', '왜냐하면'),
    (v_deck, 'vecino', '이웃'),
    (v_deck, 'dibujo', '나는 그림 그린다'),
    (v_deck, 'bien', '잘'),
    (v_deck, 'patinas', '너는 스케이트를 탄다'),
    (v_deck, 'pescas', '너는 낚시한다'),
    (v_deck, 'mal', '나쁘게'),
    (v_deck, 'yoga', '요가'),
    (v_deck, 'tango', '탱고'),
    (v_deck, 'enseñas', '너는 가르친다'),
    (v_deck, 'perdón', '죄송해요, 실례합니다'),
    (v_deck, 'curso', '과정, 코스'),
    (v_deck, 'entonces', '그러면'),
    (v_deck, 'interesante', '흥미로운'),
    (v_deck, 'son de ~', '출신이다(복수)'),
    (v_deck, 'empieza', '시작한다'),
    (v_deck, 'mañana', '내일, 아침'),
    (v_deck, 'españa', '스페인'),
    (v_deck, 'pódcast', '팟캐스트'),
    (v_deck, 'persona', '사람'),
    (v_deck, 'solo', '혼자'),
    (v_deck, 'favorito', '가장 좋아하는'),
    (v_deck, 'paseas', '너는 산책한다'),
    (v_deck, 'cuatro', '넷'),
    (v_deck, 'italia', '이탈리아'),
    (v_deck, 'árabe', '아랍어'),
    (v_deck, 'aburrido', '지루한'),
    (v_deck, 'rusia', '러시아');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 1 음식과 음료 말하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '豆腐', '두부', 'dòufu'),
    (v_deck, '和', '~와', 'hé'),
    (v_deck, '汤', '국', 'tāng'),
    (v_deck, '这是', '이것은', 'zhè shì'),
    (v_deck, '茶', '차', 'chá'),
    (v_deck, '米饭', '밥', 'mǐfàn'),
    (v_deck, '咖啡', '커피', 'kāfēi'),
    (v_deck, '水', '물', 'shuǐ'),
    (v_deck, '粥', '죽', 'zhōu'),
    (v_deck, '热', '뜨겁다', 'rè');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 2 국적에 대해 말하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '嗨', '안녕', 'hāi'),
    (v_deck, '我', '나', 'wǒ'),
    (v_deck, '是', '~이다', 'shì'),
    (v_deck, '中国', '중국', 'Zhōngguó'),
    (v_deck, '韩国', '한국', 'Hánguó'),
    (v_deck, '美国', '미국', 'Měiguó'),
    (v_deck, '英国', '영국', 'Yīngguó'),
    (v_deck, '日本', '일본', 'Rìběn'),
    (v_deck, '人', '사람', 'rén'),
    (v_deck, '你', '너', 'nǐ'),
    (v_deck, '你呢', '너는?', 'nǐ ne'),
    (v_deck, '加拿大', '캐나다', 'Jiānádà');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 3 직업에 대해 이야기하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '学生', '학생', 'xuéshēng'),
    (v_deck, '中学生', '중학생', 'zhōngxuéshēng'),
    (v_deck, '大学生', '대학생', 'dàxuéshēng'),
    (v_deck, '医生', '의사', 'yīshēng'),
    (v_deck, '老师', '선생님', 'lǎoshī'),
    (v_deck, '对不对', '맞아?', 'duì bu duì'),
    (v_deck, '说', '말하다', 'shuō'),
    (v_deck, '对', '맞다', 'duì'),
    (v_deck, '律师', '변호사', 'lǜshī');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 4 수업에 대해 이야기하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '课', '수업', 'kè'),
    (v_deck, '喜欢', '좋아하다', 'xǐhuan'),
    (v_deck, '中文', '중국어', 'Zhōngwén'),
    (v_deck, '韩文', '한국어', 'Hánwén'),
    (v_deck, '英文', '영어', 'Yīngwén'),
    (v_deck, '上', '(수업) 듣다', 'shàng'),
    (v_deck, '他', '그', 'tā'),
    (v_deck, '她', '그녀', 'tā'),
    (v_deck, '音乐', '음악', 'yīnyuè'),
    (v_deck, '数学', '수학', 'shùxué');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 5 소유 대명사 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '的', '~의', 'de'),
    (v_deck, '儿子', '아들', 'érzi'),
    (v_deck, '女儿', '딸', 'nǚ''ér'),
    (v_deck, '爸爸', '아빠', 'bàba'),
    (v_deck, '妈妈', '엄마', 'māma'),
    (v_deck, '老婆', '아내', 'lǎopo'),
    (v_deck, '老公', '남편', 'lǎogōng'),
    (v_deck, '也', '또한', 'yě');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 6 방문 장소에 대해 이야기하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '超市', '마트', 'chāoshì'),
    (v_deck, '常常', '자주', 'chángcháng'),
    (v_deck, '饭馆', '식당', 'fànguǎn'),
    (v_deck, '书店', '서점', 'shūdiàn'),
    (v_deck, '书', '책', 'shū'),
    (v_deck, '菜', '요리', 'cài'),
    (v_deck, '去', '가다', 'qù'),
    (v_deck, '吃', '먹다', 'chī'),
    (v_deck, '零食', '간식', 'língshí');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 7 음료 주문하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '牛奶', '우유', 'niúnǎi'),
    (v_deck, '奶茶', '밀크티', 'nǎichá'),
    (v_deck, '绿茶', '녹차', 'lǜchá'),
    (v_deck, '要', '원하다', 'yào'),
    (v_deck, '冰', '얼음', 'bīng'),
    (v_deck, '谢谢', '고마워', 'xièxie'),
    (v_deck, '一', '하나', 'yī'),
    (v_deck, '杯', '잔', 'bēi'),
    (v_deck, '糖', '설탕', 'táng'),
    (v_deck, '两', '두 개', 'liǎng'),
    (v_deck, '买', '사다', 'mǎi');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 8 여행 필수품 찾기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '洗手间', '화장실', 'xǐshǒujiān'),
    (v_deck, '哪里', '어디', 'nǎlǐ'),
    (v_deck, '在', '~에', 'zài'),
    (v_deck, '这里', '여기', 'zhèlǐ'),
    (v_deck, '行李', '짐', 'xíngli'),
    (v_deck, '火车', '기차', 'huǒchē'),
    (v_deck, '火车站', '기차역', 'huǒchēzhàn'),
    (v_deck, '车票', '표', 'chēpiào'),
    (v_deck, '站台', '플랫폼', 'zhàntái'),
    (v_deck, '第', '순서', 'dì'),
    (v_deck, '二', '둘', 'èr'),
    (v_deck, '三', '셋', 'sān'),
    (v_deck, '手机', '핸드폰', 'shǒujī'),
    (v_deck, '钱包', '지갑', 'qiánbāo'),
    (v_deck, '哎呀', '아이고', 'āiyā');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션1 유닛 9 자기소개 및 수업 소개하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '你好', '안녕', 'nǐ hǎo'),
    (v_deck, '李天美', '이천미(이름)', 'Lǐ Tiānměi'),
    (v_deck, '王明', '왕명(이름)', 'Wáng Míng'),
    (v_deck, '叫', '~라고 부르다', 'jiào'),
    (v_deck, '要', '원하다', 'yào'),
    (v_deck, '今天', '오늘', 'jīntiān'),
    (v_deck, '四', '넷', 'sì'),
    (v_deck, '新', '새', 'xīn'),
    (v_deck, '同学', '친구', 'tóngxué'),
    (v_deck, '历史', '역사', 'lìshǐ');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 1 형용사를 사용해 묘사하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '厨房', '주방', 'chúfáng'),
    (v_deck, '卧室', '침실', 'wòshì'),
    (v_deck, '房子', '집', 'fángzi'),
    (v_deck, '大', '크다', 'dà'),
    (v_deck, '小', '작다', 'xiǎo'),
    (v_deck, '很', '매우', 'hěn'),
    (v_deck, '漂亮', '예쁘다', 'piàoliang'),
    (v_deck, '公寓', '아파트', 'gōngyù'),
    (v_deck, '床', '침대', 'chuáng'),
    (v_deck, '电视', 'TV', 'diànshì'),
    (v_deck, '沙发', '소파', 'shāfā'),
    (v_deck, '舒服', '편하다', 'shūfu'),
    (v_deck, '冰箱', '냉장고', 'bīngxiāng'),
    (v_deck, '桌子', '책상', 'zhuōzi'),
    (v_deck, '旧', '낡다', 'jiù'),
    (v_deck, '乱', '어지럽다', 'luàn'),
    (v_deck, '只', '마리(동물 단위)', 'zhī'),
    (v_deck, '客厅', '거실', 'kètīng'),
    (v_deck, '哇', '와', 'wa');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 2 베이징 여행하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '北京', '베이징', 'Běijīng'),
    (v_deck, '夏天', '여름', 'xiàtiān'),
    (v_deck, '冬天', '겨울', 'dōngtiān'),
    (v_deck, '春天', '봄', 'chūntiān'),
    (v_deck, '秋天', '가을', 'qiūtiān'),
    (v_deck, '长城', '만리장성', 'Chángchéng'),
    (v_deck, '故宫', '자금성', 'Gùgōng'),
    (v_deck, '有名', '유명하다', 'yǒumíng'),
    (v_deck, '热闹', '번화하다', 'rènào'),
    (v_deck, '好玩儿', '재미있다', 'hǎowánr'),
    (v_deck, '老家', '고향', 'lǎojiā'),
    (v_deck, '冷', '춥다', 'lěng'),
    (v_deck, '特别', '특별하다', 'tèbié'),
    (v_deck, '时候', '때', 'shíhou'),
    (v_deck, '人们', '사람들', 'rénmen'),
    (v_deck, '动物园', '동물원', 'dòngwùyuán'),
    (v_deck, '门票', '입장권', 'ménpiào'),
    (v_deck, '远', '멀다', 'yuǎn'),
    (v_deck, '贵', '비싸다', 'guì'),
    (v_deck, '火锅', '훠궈', 'huǒguō'),
    (v_deck, '烤鸭', '베이징덕', 'kǎoyā'),
    (v_deck, '辣', '맵다', 'là'),
    (v_deck, '好吃', '맛있다', 'hǎochī');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 3 제안을 나타내는 조사 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '博物馆', '박물관', 'bówùguǎn'),
    (v_deck, '周末', '주말', 'zhōumò'),
    (v_deck, '吧', '~하자', 'ba'),
    (v_deck, '地铁', '지하철', 'dìtiě'),
    (v_deck, '坐', '타다', 'zuò'),
    (v_deck, '电影', '영화', 'diànyǐng'),
    (v_deck, '蛋糕', '케이크', 'dàngāo'),
    (v_deck, '水果', '과일', 'shuǐguǒ'),
    (v_deck, '好的', '좋다', 'hǎo de'),
    (v_deck, '空儿', '시간(여유)', 'kòngr'),
    (v_deck, '公交车', '버스', 'gōngjiāochē'),
    (v_deck, '快', '빠르다', 'kuài'),
    (v_deck, '爱情', '사랑', 'àiqíng'),
    (v_deck, '爆米花', '팝콘', 'bàomǐhuā'),
    (v_deck, '一些', '조금', 'yìxiē'),
    (v_deck, '带', '가져가다', 'dài'),
    (v_deck, '家', '집', 'jiā'),
    (v_deck, '果汁', '주스', 'guǒzhī'),
    (v_deck, '碗饭', '밥 한 그릇', 'wǎnfàn'),
    (v_deck, '饺子', '만두', 'jiǎozi'),
    (v_deck, '做', '만들다', 'zuò'),
    (v_deck, '喝', '마시다', 'hē');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 4 명령어 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '土豆', '감자', 'tǔdòu'),
    (v_deck, '西红柿', '토마토', 'xīhóngshì'),
    (v_deck, '几', '몇', 'jǐ'),
    (v_deck, '先', '먼저', 'xiān'),
    (v_deck, '做饭', '요리하다', 'zuòfàn'),
    (v_deck, '盐', '소금', 'yán'),
    (v_deck, '盘子', '접시', 'pánzi'),
    (v_deck, '小心', '조심하다', 'xiǎoxīn'),
    (v_deck, '放', '놓다', 'fàng'),
    (v_deck, '洗', '씻다', 'xǐ'),
    (v_deck, '肉', '고기', 'ròu'),
    (v_deck, '手', '손', 'shǒu'),
    (v_deck, '蔬菜', '채소', 'shūcài'),
    (v_deck, '爷爷', '할아버지', 'yéye'),
    (v_deck, '多', '많다', 'duō'),
    (v_deck, '杯子', '컵', 'bēizi'),
    (v_deck, '吃饭', '밥 먹다', 'chīfàn'),
    (v_deck, '用', '사용하다', 'yòng'),
    (v_deck, '别', '~하지 마', 'bié'),
    (v_deck, '别玩', '놀지 마', 'bié wán'),
    (v_deck, '冰淇淋', '아이스크림', 'bīngqílín'),
    (v_deck, '碗', '그릇', 'wǎn'),
    (v_deck, '洗碗机', '식기세척기', 'xǐwǎnjī'),
    (v_deck, '现在', '지금', 'xiànzài'),
    (v_deck, '擦', '닦다', 'cā');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 5 능력 표현하는 조동사 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '俱乐部', '동아리', 'jùlèbù'),
    (v_deck, '喜剧', '코미디', 'xǐjù'),
    (v_deck, '有趣', '재미있다', 'yǒuqù'),
    (v_deck, '足球', '축구', 'zúqiú'),
    (v_deck, '踢', '차다', 'tī'),
    (v_deck, '棒球', '야구', 'bàngqiú'),
    (v_deck, '一起', '함께', 'yìqǐ'),
    (v_deck, '会', '~할 수 있다', 'huì'),
    (v_deck, '钢琴', '피아노', 'gāngqín'),
    (v_deck, '弹', '연주하다', 'tán'),
    (v_deck, '吉他', '기타', 'jítā'),
    (v_deck, '流行', '유행하다', 'liúxíng'),
    (v_deck, '唱歌', '노래하다', 'chànggē'),
    (v_deck, '西班牙语', '스페인어', 'Xībānyáyǔ'),
    (v_deck, '法语', '프랑스어', 'Fǎyǔ'),
    (v_deck, '练习', '연습하다', 'liànxí'),
    (v_deck, '语言', '언어', 'yǔyán'),
    (v_deck, '种', '종류', 'zhǒng'),
    (v_deck, '面包', '빵', 'miànbāo'),
    (v_deck, '面条', '국수', 'miàntiáo'),
    (v_deck, '饼干', '과자', 'bǐnggān'),
    (v_deck, '烤', '굽다', 'kǎo'),
    (v_deck, '泰国', '태국', 'Tàiguó');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 6 허락 구하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '巧克力', '초콜릿', 'qiǎokèlì'),
    (v_deck, '不行', '안 된다', 'bùxíng'),
    (v_deck, '健康', '건강하다', 'jiànkāng'),
    (v_deck, '想', '원하다', 'xiǎng'),
    (v_deck, '狗', '개', 'gǒu'),
    (v_deck, '玩具', '장난감', 'wánjù'),
    (v_deck, '只', '마리(동물 단위)', 'zhī'),
    (v_deck, '兔子', '토끼', 'tùzi'),
    (v_deck, '养', '기르다', 'yǎng'),
    (v_deck, '可爱', '귀엽다', 'kě''ài'),
    (v_deck, '姐姐', '언니', 'jiějie'),
    (v_deck, '哥哥', '오빠', 'gēge'),
    (v_deck, '商场', '쇼핑몰', 'shāngchǎng'),
    (v_deck, '出去玩儿', '놀러 나가다', 'chūqù wánr'),
    (v_deck, '朋友', '친구', 'péngyou'),
    (v_deck, '可以', '가능하다', 'kěyǐ'),
    (v_deck, '电脑', '컴퓨터', 'diànnǎo'),
    (v_deck, '可乐', '콜라', 'kělè'),
    (v_deck, '游戏', '게임', 'yóuxì'),
    (v_deck, '玩', '놀다', 'wán'),
    (v_deck, '借', '빌리다', 'jiè'),
    (v_deck, '窗户', '창문', 'chuānghu'),
    (v_deck, '休息', '쉬다', 'xiūxi'),
    (v_deck, '累', '피곤하다', 'lèi'),
    (v_deck, '扫', '쓸다', 'sǎo'),
    (v_deck, '地', '바닥', 'dì');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 7 집을 청소하고 정리하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '邻居', '이웃', 'línjū'),
    (v_deck, '室友', '룸메이트', 'shìyǒu'),
    (v_deck, '找', '찾다', 'zhǎo'),
    (v_deck, '吵', '시끄럽다', 'chǎo'),
    (v_deck, '这个', '이것', 'zhège'),
    (v_deck, '地方', '장소', 'dìfang'),
    (v_deck, '椅子', '의자', 'yǐzi'),
    (v_deck, '台灯', '스탠드', 'táidēng'),
    (v_deck, '书架', '책장', 'shūjià'),
    (v_deck, '重', '무겁다', 'zhòng'),
    (v_deck, '那个', '저것', 'nàge'),
    (v_deck, '衣服', '옷', 'yīfu'),
    (v_deck, '帽子', '모자', 'màozi'),
    (v_deck, '好看', '보기 좋다', 'hǎokàn'),
    (v_deck, '还', '아직', 'hái'),
    (v_deck, '这些', '이것들', 'zhèxiē'),
    (v_deck, '那些', '저것들', 'nàxiē'),
    (v_deck, '勺子', '숟가락', 'sháozi'),
    (v_deck, '筷子', '젓가락', 'kuàizi'),
    (v_deck, '都', '모두', 'dōu'),
    (v_deck, '扔掉', '버리다', 'rēngdiào'),
    (v_deck, '吸尘器', '청소기', 'xīchénqì'),
    (v_deck, '打扫', '청소하다', 'dǎsǎo'),
    (v_deck, '脏', '더럽다', 'zāng'),
    (v_deck, '拖把', '대걸레', 'tuōbǎ'),
    (v_deck, '东西', '물건', 'dōngxi');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 8 현재 진행형 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '妹妹', '여동생', 'mèimei'),
    (v_deck, '报纸', '신문', 'bàozhǐ'),
    (v_deck, '早饭', '아침밥', 'zǎofàn'),
    (v_deck, '星期六', '토요일', 'xīngqīliù'),
    (v_deck, '在', '~하고 있다', 'zài'),
    (v_deck, '睡觉', '자다', 'shuìjiào'),
    (v_deck, '忙', '바쁘다', 'máng'),
    (v_deck, '干净', '깨끗하다', 'gānjìng'),
    (v_deck, '需要', '필요하다', 'xūyào'),
    (v_deck, '帮助', '돕다', 'bāngzhù'),
    (v_deck, '小提琴', '바이올린', 'xiǎotíqín'),
    (v_deck, '拉', '(악기) 연주하다', 'lā'),
    (v_deck, '听', '듣다', 'tīng'),
    (v_deck, '摇滚', '록(음악)', 'yáogǔn'),
    (v_deck, '没', '없다', 'méi'),
    (v_deck, '喂', '(전화) 여보', 'wéi'),
    (v_deck, '是我', '나야', 'shì wǒ'),
    (v_deck, '上网', '인터넷 하다', 'shàngwǎng'),
    (v_deck, '什么', '무엇', 'shénme'),
    (v_deck, '做什么', '뭐 하다', 'zuò shénme'),
    (v_deck, '飞盘', '프리스비', 'fēipán'),
    (v_deck, '女孩儿', '여자아이', 'nǚháir'),
    (v_deck, '他们', '그들', 'tāmen'),
    (v_deck, '卖', '팔다', 'mài'),
    (v_deck, '人', '사람', 'rén');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 9 의료 도움 요청하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '医院', '병원', 'yīyuàn'),
    (v_deck, '发烧', '열나다', 'fāshāo'),
    (v_deck, '怎么了', '왜 그래', 'zěnme le'),
    (v_deck, '了', '~했다', 'le'),
    (v_deck, '不舒服', '아프다', 'bù shūfu'),
    (v_deck, '早上', '아침', 'zǎoshang'),
    (v_deck, '肚子', '배', 'dùzi'),
    (v_deck, '疼', '아프다', 'téng'),
    (v_deck, '头', '머리', 'tóu'),
    (v_deck, '下午', '오후', 'xiàwǔ'),
    (v_deck, '药店', '약국', 'yàodiàn'),
    (v_deck, '药', '약', 'yào'),
    (v_deck, '跟', '~와 함께', 'gēn'),
    (v_deck, '请', '요청하다', 'qǐng'),
    (v_deck, '假', '휴가', 'jià'),
    (v_deck, '花', '꽃', 'huā'),
    (v_deck, '束', '다발', 'shù'),
    (v_deck, '来', '오다', 'lái'),
    (v_deck, '开心', '기쁘다', 'kāixīn'),
    (v_deck, '给', '주다', 'gěi'),
    (v_deck, '煮', '끓이다', 'zhǔ'),
    (v_deck, '少', '적다', 'shǎo'),
    (v_deck, '量体温', '체온 재다', 'liáng tǐwēn'),
    (v_deck, '应该', '~해야 한다', 'yīnggāi');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 10 생일 파티 계획하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '派对', '파티', 'pàiduì'),
    (v_deck, '星期天', '일요일', 'xīngqītiān'),
    (v_deck, '生日', '생일', 'shēngrì'),
    (v_deck, '开', '열다', 'kāi'),
    (v_deck, '下个', '다음', 'xià ge'),
    (v_deck, '邀请', '초대하다', 'yāoqǐng'),
    (v_deck, '五', '다섯', 'wǔ'),
    (v_deck, '礼物', '선물', 'lǐwù'),
    (v_deck, '饮料', '음료', 'yǐnliào'),
    (v_deck, '准备', '준비하다', 'zhǔnbèi'),
    (v_deck, '气球', '풍선', 'qìqiú'),
    (v_deck, '奶奶', '할머니', 'nǎinai'),
    (v_deck, '告诉', '알려주다', 'gàosu'),
    (v_deck, '明天', '내일', 'míngtiān'),
    (v_deck, '惊喜', '서프라이즈', 'jīngxǐ'),
    (v_deck, '蜡烛', '초', 'làzhú'),
    (v_deck, '鱼', '생선', 'yú'),
    (v_deck, '薯片', '감자칩', 'shǔpiàn'),
    (v_deck, '菜', '요리', 'cài'),
    (v_deck, '领带', '넥타이', 'lǐngdài'),
    (v_deck, '围巾', '목도리', 'wéijīn'),
    (v_deck, '项链', '목걸이', 'xiàngliàn'),
    (v_deck, '条', '(길쭉한 것 단위)', 'tiáo'),
    (v_deck, '快乐', '즐겁다', 'kuàilè');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 11 캠퍼스에서 길 묻기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '学校', '학교', 'xuéxiào'),
    (v_deck, '图书馆', '도서관', 'túshūguǎn'),
    (v_deck, '地铁站', '지하철역', 'dìtiězhàn'),
    (v_deck, '请问', '실례하지만', 'qǐngwèn'),
    (v_deck, '里面', '안쪽', 'lǐmiàn'),
    (v_deck, '旁边', '옆', 'pángbiān'),
    (v_deck, '操场', '운동장', 'cāochǎng'),
    (v_deck, '校园', '캠퍼스', 'xiàoyuán'),
    (v_deck, '真', '정말', 'zhēn'),
    (v_deck, '参观', '견학하다', 'cānguān'),
    (v_deck, '外面', '밖', 'wàimiàn'),
    (v_deck, '六', '여섯', 'liù'),
    (v_deck, '高', '높다', 'gāo'),
    (v_deck, '教学楼', '강의동', 'jiàoxuélóu'),
    (v_deck, '号', '번호', 'hào'),
    (v_deck, '后面', '뒤', 'hòumiàn'),
    (v_deck, '停车场', '주차장', 'tíngchēchǎng'),
    (v_deck, '宿舍', '기숙사', 'sùshè'),
    (v_deck, '食堂', '식당', 'shítáng'),
    (v_deck, '安静', '조용하다', 'ānjìng'),
    (v_deck, '前面', '앞', 'qiánmiàn'),
    (v_deck, '体育馆', '체육관', 'tǐyùguǎn'),
    (v_deck, '游泳池', '수영장', 'yóuyǒngchí'),
    (v_deck, '活动', '활동', 'huódòng'),
    (v_deck, '晚上', '저녁', 'wǎnshang'),
    (v_deck, '参加', '참가하다', 'cānjiā');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 12 비교급 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '请进', '들어오세요', 'qǐng jìn'),
    (v_deck, '书房', '서재', 'shūfáng'),
    (v_deck, '看', '보다', 'kàn'),
    (v_deck, '亮', '밝다', 'liàng'),
    (v_deck, '比', '~보다', 'bǐ'),
    (v_deck, '苹果', '사과', 'píngguǒ'),
    (v_deck, '照片', '사진', 'zhàopiàn'),
    (v_deck, '家人', '가족', 'jiārén'),
    (v_deck, '西瓜', '수박', 'xīguā'),
    (v_deck, '好喝', '맛있다(음료)', 'hǎohē'),
    (v_deck, '猫', '고양이', 'māo'),
    (v_deck, '大', '크다', 'dà'),
    (v_deck, '聪明', '똑똑하다', 'cōngming'),
    (v_deck, '弟弟', '남동생', 'dìdi'),
    (v_deck, '没有', '없다', 'méiyǒu'),
    (v_deck, '牛肉', '소고기', 'niúròu'),
    (v_deck, '鸡肉', '닭고기', 'jīròu'),
    (v_deck, '玉米', '옥수수', 'yùmǐ'),
    (v_deck, '新鲜', '신선하다', 'xīnxiān'),
    (v_deck, '歌手', '가수', 'gēshǒu'),
    (v_deck, '节目', '프로그램', 'jiémù'),
    (v_deck, '歌', '노래', 'gē'),
    (v_deck, '首', '(노래 단위)', 'shǒu'),
    (v_deck, '好听', '듣기 좋다', 'hǎotīng');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 13 어린 시절 이야기하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '人', '사람', 'rén'),
    (v_deck, '上海', '상하이', 'Shànghǎi'),
    (v_deck, '在', '~에', 'zài'),
    (v_deck, '出生', '태어나다', 'chūshēng'),
    (v_deck, '长大', '자라다', 'zhǎngdà'),
    (v_deck, '九', '아홉', 'jiǔ'),
    (v_deck, '中学', '중학교', 'zhōngxué'),
    (v_deck, '小学', '초등학교', 'xiǎoxué'),
    (v_deck, '很多', '많다', 'hěn duō'),
    (v_deck, '年', '년', 'nián'),
    (v_deck, '零', '영', 'líng'),
    (v_deck, '上', '올라가다', 'shàng'),
    (v_deck, '七', '일곱', 'qī'),
    (v_deck, '香港', '홍콩', 'Xiānggǎng'),
    (v_deck, '工作', '일하다', 'gōngzuò'),
    (v_deck, '生活', '생활하다', 'shēnghuó'),
    (v_deck, '出国', '출국하다', 'chūguó'),
    (v_deck, '回', '돌아가다', 'huí'),
    (v_deck, '旅行', '여행하다', 'lǚxíng'),
    (v_deck, '岁', '살', 'suì'),
    (v_deck, '前', '전', 'qián'),
    (v_deck, '八', '여덟', 'bā'),
    (v_deck, '桌游', '보드게임', 'zhuōyóu'),
    (v_deck, '动画片', '애니메이션', 'dònghuàpiàn'),
    (v_deck, '小时候', '어릴 때', 'xiǎoshíhou'),
    (v_deck, '流行', '유행하다', 'liúxíng');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 14 활동 계획 세우기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '出门', '외출하다', 'chūmén'),
    (v_deck, '电话', '전화', 'diànhuà'),
    (v_deck, '打电话', '전화하다', 'dǎ diànhuà'),
    (v_deck, '在家', '집에 있다', 'zài jiā'),
    (v_deck, '乒乓球', '탁구', 'pīngpāngqiú'),
    (v_deck, '后天', '모레', 'hòutiān'),
    (v_deck, '学', '배우다', 'xué'),
    (v_deck, '有事儿', '일이 있다', 'yǒu shìr'),
    (v_deck, '外地', '다른 지역', 'wàidì'),
    (v_deck, '老朋友', '오랜 친구', 'lǎo péngyou'),
    (v_deck, '想', '원하다', 'xiǎng'),
    (v_deck, '见', '만나다', 'jiàn'),
    (v_deck, '要', '원하다', 'yào'),
    (v_deck, '天气', '날씨', 'tiānqì'),
    (v_deck, '好啊', '좋다', 'hǎo a'),
    (v_deck, '爬山', '등산하다', 'páshān'),
    (v_deck, '钓鱼', '낚시하다', 'diàoyú'),
    (v_deck, '加入', '참여하다', 'jiārù'),
    (v_deck, '加油', '힘내다', 'jiāyóu'),
    (v_deck, '星期', '주', 'xīngqī'),
    (v_deck, '紧张', '긴장하다', 'jǐnzhāng'),
    (v_deck, '考试', '시험', 'kǎoshì'),
    (v_deck, '复习', '복습하다', 'fùxí');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 15 시간 표현 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '机场', '공항', 'jīchǎng'),
    (v_deck, '脸', '얼굴', 'liǎn'),
    (v_deck, '洗脸', '세수하다', 'xǐ liǎn'),
    (v_deck, '点', '시 (시간 단위)', 'diǎn'),
    (v_deck, '出租车', '택시', 'chūzūchē'),
    (v_deck, '半', '반', 'bàn'),
    (v_deck, '到', '도착하다', 'dào'),
    (v_deck, '出发', '출발하다', 'chūfā'),
    (v_deck, '护照', '여권', 'hùzhào'),
    (v_deck, '飞机', '비행기', 'fēijī'),
    (v_deck, '别着急', '서두르지 마', 'bié zháojí'),
    (v_deck, '起飞', '이륙하다', 'qǐfēi'),
    (v_deck, '酒店', '호텔', 'jiǔdiàn'),
    (v_deck, '上午', '오전', 'shàngwǔ'),
    (v_deck, '纽约', '뉴욕', 'Niǔyuē'),
    (v_deck, '分', '분 (시간 단위)', 'fēn'),
    (v_deck, '公交站', '버스정류장', 'gōngjiāozhàn'),
    (v_deck, '哪里', '어디', 'nǎlǐ'),
    (v_deck, '对面', '맞은편', 'duìmiàn');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 16 옷 쇼핑하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '车', '차', 'chē'),
    (v_deck, '袜子', '양말', 'wàzi'),
    (v_deck, '鞋', '신발', 'xié'),
    (v_deck, '双', '(켤레 세는 단위) 쌍', 'shuāng'),
    (v_deck, '开', '운전하다/열다', 'kāi'),
    (v_deck, '逛街', '쇼핑하다', 'guàngjiē'),
    (v_deck, '买不买', '살까 말까', 'mǎi bù mǎi'),
    (v_deck, '手套', '장갑', 'shǒutào'),
    (v_deck, '厚', '두껍다', 'hòu'),
    (v_deck, '试衣间', '탈의실', 'shìyījiān'),
    (v_deck, '硬', '딱딱하다', 'yìng'),
    (v_deck, '有点儿', '약간/조금', 'yǒudiǎnr'),
    (v_deck, '白色', '흰색', 'báisè'),
    (v_deck, '连衣裙', '원피스', 'liányīqún'),
    (v_deck, '裤子', '바지', 'kùzi'),
    (v_deck, '紧', '꽉 끼다', 'jǐn'),
    (v_deck, '长', '길다', 'cháng'),
    (v_deck, '皮带', '벨트', 'pídài'),
    (v_deck, '黑色', '검은색', 'hēisè'),
    (v_deck, '牌子', '브랜드', 'páizi'),
    (v_deck, '打折', '할인하다', 'dǎzhé'),
    (v_deck, '便宜', '싸다', 'piányi'),
    (v_deck, '披萨', '피자', 'pīsà'),
    (v_deck, '别的', '다른 것', 'biéde'),
    (v_deck, '渇', '목마르다', 'kě'),
    (v_deck, '饿', '배고프다', 'è');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 17 콘서트에 가기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '城市', '도시', 'chéngshì'),
    (v_deck, '计划', '계획(하다)', 'jìhuà'),
    (v_deck, '假期', '휴가/방학', 'jiàqī'),
    (v_deck, '国外', '외국', 'guówài'),
    (v_deck, '哪些', '어떤', 'nǎxiē'),
    (v_deck, '演唱会', '콘서트', 'yǎnchànghuì'),
    (v_deck, '难', '어렵다', 'nán'),
    (v_deck, '滑雪', '스키 타다', 'huá xuě'),
    (v_deck, '售票处', '매표소', 'shòupiàochù'),
    (v_deck, '在网上', '인터넷에서', 'zài wǎngshàng'),
    (v_deck, '举行', '열다', 'jǔxíng'),
    (v_deck, '等', '기다리다', 'děng'),
    (v_deck, '排队', '줄서다', 'pái duì'),
    (v_deck, '入口', '입구', 'rùkǒu'),
    (v_deck, '见面', '만나다', 'jiàn miàn'),
    (v_deck, '停车', '주차하다', 'tíng chē'),
    (v_deck, '座位', '좌석', 'zuòwèi'),
    (v_deck, '纪念品', '기념품', 'jìniànpǐn'),
    (v_deck, '兴奋', '흥분하다', 'xīngfèn'),
    (v_deck, '开始', '시작하다', 'kāishǐ'),
    (v_deck, '拍', '(사진)찍다', 'pāi');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 18 질문하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '衬衫', '셔츠', 'chènshān'),
    (v_deck, '公司', '회사', 'gōngsī'),
    (v_deck, '件', '(옷 세는 단위)벌', 'jiàn'),
    (v_deck, '穿', '입다', 'chuān'),
    (v_deck, '办公室', '사무실', 'bàngōngshì'),
    (v_deck, '同事', '동료', 'tóngshì'),
    (v_deck, '早上好', '좋은 아침', 'zǎoshang hǎo'),
    (v_deck, '会议室', '회의실', 'huìyìshì'),
    (v_deck, '层', '층', 'céng'),
    (v_deck, '欢迎', '환영하다', 'huānyíng'),
    (v_deck, '先生', '선생/님(남성존칭)', 'xiānsheng'),
    (v_deck, '李先生', '이 선생님', 'Lǐ xiānsheng'),
    (v_deck, '热情', '열정적이다/친절하다', 'rèqíng'),
    (v_deck, '赵小月', '자오샤오웨(이름)', 'Zhào Xiǎoyuè'),
    (v_deck, '谁', '누구', 'shéi / shuí'),
    (v_deck, '重要', '중요하다', 'zhòngyào'),
    (v_deck, '会', '회의/할 수 있다/할 것이다', 'huì'),
    (v_deck, '经理', '매니저', 'jīnglǐ'),
    (v_deck, '王经理', '왕 매니저', 'Wáng jīnglǐ'),
    (v_deck, '酒', '술', 'jiǔ'),
    (v_deck, '老板', '사장님', 'lǎobǎn'),
    (v_deck, '点菜', '(요리)주문하다', 'diǎn cài'),
    (v_deck, '订', '예약하다/주문하다', 'dìng'),
    (v_deck, '今晚', '오늘 밤', 'jīnwǎn');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 19 소유 표현하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '书包', '책가방', 'shūbāo'),
    (v_deck, '不知道', '모르다', 'bù zhīdào'),
    (v_deck, '刚刚', '방금, 마침, 이제 막', 'gānggāng'),
    (v_deck, '发现', '발견하다, 알아차리다', 'fāxiàn'),
    (v_deck, '雨伞', '우산', 'yǔsǎn'),
    (v_deck, '红色', '빨간색', 'hóngsè'),
    (v_deck, '小姐', '아가씨, ~양', 'xiǎojiě'),
    (v_deck, '丢', '잃어버리다, 던지다, 버리다', 'diū'),
    (v_deck, '蓝色', '파란색', 'lánsè'),
    (v_deck, '名字', '이름', 'míngzi'),
    (v_deck, '身份证', '신분증', 'shēnfènzhèng'),
    (v_deck, '叫', '~라고 부르다', 'jiào'),
    (v_deck, '张华', '장화(이름)', 'Zhāng Huá'),
    (v_deck, '好像', '마치 ~인 것 같다, 비슷하다', 'hǎoxiàng'),
    (v_deck, '水杯', '물컵', 'shuǐbēi'),
    (v_deck, '绿色', '초록색', 'lǜsè'),
    (v_deck, '本', '권', 'běn'),
    (v_deck, '词典', '사전', 'cídiǎn'),
    (v_deck, '还', '아직, 더, 게다가', 'hái');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 20 감정 표현하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '小说', '소설', 'xiǎoshuō'),
    (v_deck, '聊天', '이야기하다', 'liáotiān'),
    (v_deck, '平时', '평소', 'píngshí'),
    (v_deck, '最', '가장, 제일', 'zuì'),
    (v_deck, '家务', '집안일', 'jiāwù'),
    (v_deck, '讨厌', '싫어하다, 귀찮다', 'tǎoyàn'),
    (v_deck, '无聊', '지루하다, 심심하다', 'wúliáo'),
    (v_deck, '做', '하다, 만들다', 'zuò'),
    (v_deck, '蜘蛛', '거미', 'zhīzhū'),
    (v_deck, '天呐', '맙소사', 'tiān na'),
    (v_deck, '蛇', '뱀', 'shé'),
    (v_deck, '怕', '무서워하다', 'pà'),
    (v_deck, '危险', '위험하다', 'wēixiǎn'),
    (v_deck, '沙拉', '샐러드', 'shālā'),
    (v_deck, '快餐', '패스트푸드', 'kuàicān'),
    (v_deck, '四川', '쓰촨', 'Sìchuān'),
    (v_deck, '红茶', '홍차', 'hóngchá'),
    (v_deck, '日语', '일본어', 'Rìyǔ'),
    (v_deck, '汉字', '한자', 'Hànzì'),
    (v_deck, '写', '쓰다', 'xiě'),
    (v_deck, '容易', '쉽다, 용이하다', 'róngyì');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 21 날씨에 대해 이야기하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '天气', '날씨', 'tiānqì'),
    (v_deck, '今年', '올해', 'jīnnián'),
    (v_deck, '挺', '매우, 꽤', 'tǐng'),
    (v_deck, '冷的', '추운 것', 'lěng de'),
    (v_deck, '大衣', '코트, 외투', 'dàyī'),
    (v_deck, '戴', '(모자, 안경 등을) 쓰다', 'dài'),
    (v_deck, '太', '너무, 아주', 'tài'),
    (v_deck, '晴天', '맑은 날', 'qíngtiān'),
    (v_deck, '海边', '해변, 바닷가', 'hǎibiān'),
    (v_deck, '暖和', '따뜻하다', 'nuǎnhuo'),
    (v_deck, '一起', '함께, 같이', 'yìqǐ'),
    (v_deck, '毛衣', '스웨터', 'máoyī'),
    (v_deck, '有风', '바람이 불다', 'yǒu fēng'),
    (v_deck, '咖啡馆', '카페', 'kāfēiguǎn'),
    (v_deck, '记得', '기억하다', 'jìde'),
    (v_deck, '门', '문', 'mén'),
    (v_deck, '关', '닫다, 끄다', 'guān'),
    (v_deck, '雨衣', '우비', 'yǔyī'),
    (v_deck, '有雨', '비가 오다', 'yǒu yǔ');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 22 친구에 대해 이야기하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '好朋友', '좋은 친구', 'hǎo péngyou'),
    (v_deck, '多大', '나이가 몇 살인가', 'duō dà'),
    (v_deck, '岁', '살, 세', 'suì'),
    (v_deck, '小', '나이가 적다, 작다', 'xiǎo'),
    (v_deck, '很多', '매우 많다', 'hěn duō'),
    (v_deck, '家', '집, 가정', 'jiā'),
    (v_deck, '男朋友', '남자친구', 'nánpéngyou'),
    (v_deck, '几口人', '몇 식구', 'jǐ kǒu rén'),
    (v_deck, '那', '그, 저, 그렇다면', 'nà'),
    (v_deck, '懒', '게으르다', 'lǎn'),
    (v_deck, '跳舞', '춤을 추다', 'tiàowǔ'),
    (v_deck, '滑冰', '스케이트를 타다', 'huábīng'),
    (v_deck, '厉害', '대단하다, 엄청나다', 'lìhai'),
    (v_deck, '农村', '농촌, 시골', 'nóngcūn'),
    (v_deck, '女朋友', '여자친구', 'nǚpéngyou'),
    (v_deck, '上学', '학교에 다니다', 'shàngxué'),
    (v_deck, '住', '살다, 거주하다', 'zhù'),
    (v_deck, '麻将', '마작', 'májiàng'),
    (v_deck, '爱好', '취미', 'àihào'),
    (v_deck, '太棒了', '대단하다, 최고다', 'tài bàng le'),
    (v_deck, '电视剧', '드라마', 'diànshìjù'),
    (v_deck, '不同', '다르다', 'bùtóng');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 23 일상 루틴 설명하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '新闻', '뉴스', 'xīnwén'),
    (v_deck, '刷牙', '양치질하다', 'shuāyá'),
    (v_deck, '起床', '일어나다, 기상하다', 'qǐchuáng'),
    (v_deck, '每天', '매일', 'měitiān'),
    (v_deck, '一边', '~하면서', 'yìbiān'),
    (v_deck, '自行车', '자전거', 'zìxíngchē'),
    (v_deck, '走路', '걸어가다', 'zǒu lù'),
    (v_deck, '上班', '출근하다', 'shàngbān'),
    (v_deck, '方便', '편리하다', 'fāngbiàn'),
    (v_deck, '骑', '(자전거, 말을) 타다', 'qí'),
    (v_deck, '钥匙', '열쇠', 'yàoshi'),
    (v_deck, '忘', '잊다, 깜빡하다', 'wàng'),
    (v_deck, '下班', '퇴근하다', 'xiàbān'),
    (v_deck, '有时候', '가끔, 때로는', 'yǒu shíhou'),
    (v_deck, '日记', '일기', 'rìjì'),
    (v_deck, '作家', '작가', 'zuòjiā'),
    (v_deck, '漫画', '만화', 'mànhuà'),
    (v_deck, '晚安', '안녕히 주무세요', 'wǎn''ān'),
    (v_deck, '睡觉', '잠을 자다', 'shuìjiào'),
    (v_deck, '洗澡', '목욕하다, 샤워하다', 'xǐzǎo');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 24 일상 업무 관리하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '鸡蛋', '달걀, 계란', 'jīdàn'),
    (v_deck, '星期二', '화요일', 'xīngqī''èr'),
    (v_deck, '快', '빠르다, 곧', 'kuài'),
    (v_deck, '换', '바꾸다, 환전하다', 'huàn'),
    (v_deck, '午饭', '점심식사', 'wǔfàn'),
    (v_deck, '时间', '시간', 'shíjiān'),
    (v_deck, '帮', '돕다', 'bāng'),
    (v_deck, '然后', '그러고 나서', 'ránhòu'),
    (v_deck, '马上', '즉시, 바로', 'mǎshàng'),
    (v_deck, '外卖', '배달 음식', 'wàimài'),
    (v_deck, '接', '받다, 마중하다', 'jiē'),
    (v_deck, '点', '시, 주문하다', 'diǎn'),
    (v_deck, '汽水', '탄산음료', 'qìshuǐ'),
    (v_deck, '辣椒', '고추', 'làjiāo'),
    (v_deck, '没问题', '문제없다', 'méi wèntí'),
    (v_deck, '怎么样', '어떠하다', 'zěnmeyàng'),
    (v_deck, '作业', '숙제, 과제', 'zuòyè'),
    (v_deck, '困', '졸리다', 'kùn'),
    (v_deck, '散步', '산책하다', 'sànbù'),
    (v_deck, '早点儿', '조금 일찍', 'zǎodiǎnr');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 25 온라인 쇼핑하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '网站', '웹사이트', 'wǎngzhàn'),
    (v_deck, '家具', '가구', 'jiājù'),
    (v_deck, '账号', '계정', 'zhànghào'),
    (v_deck, '不错', '좋다, 훌륭하다', 'búcuò'),
    (v_deck, '包', '가방', 'bāo'),
    (v_deck, '手表', '손목시계', 'shǒubiǎo'),
    (v_deck, '块', '위안(화폐 단위)', 'kuài'),
    (v_deck, '百', '백(100)', 'bǎi'),
    (v_deck, '时尚', '유행, 패션', 'shíshàng'),
    (v_deck, '运动鞋', '운동화', 'yùndòngxié'),
    (v_deck, '打五折', '50% 할인하다', 'dǎ wǔ zhé'),
    (v_deck, '穿', '입다, 신다', 'chuān'),
    (v_deck, '多少钱', '얼마입니까', 'duōshao qián'),
    (v_deck, '信用卡', '신용카드', 'xìnyòngkǎ'),
    (v_deck, '网', '인터넷, 망', 'wǎng'),
    (v_deck, '一共', '모두, 합계', 'yígòng'),
    (v_deck, '慢', '느리다', 'màn'),
    (v_deck, '服务', '서비스', 'fúwù'),
    (v_deck, '号', '번호, 사이즈', 'hào'),
    (v_deck, '订单', '주문서', 'dìngdān'),
    (v_deck, '满意', '만족하다', 'mǎnyì'),
    (v_deck, '退', '환불하다, 반품하다', 'tuì');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 26 임대 세부사항 논의하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '张', '장(침대, 책상 등을 세는 단위)', 'zhāng'),
    (v_deck, '阳台', '발코니, 베란다', 'yángtái'),
    (v_deck, '租', '임대하다', 'zū'),
    (v_deck, '里', '안, 속', 'lǐ'),
    (v_deck, '衣柜', '옷장', 'yīguì'),
    (v_deck, '空调', '에어컨', 'kōngtiáo'),
    (v_deck, '当然', '당연히, 물론', 'dāngrán'),
    (v_deck, '换', '바꾸다, 교체하다', 'huàn'),
    (v_deck, '墙', '벽', 'qiáng'),
    (v_deck, '镜子', '거울', 'jìngzi'),
    (v_deck, '画儿', '그림', 'huàr'),
    (v_deck, '颜色', '색상, 색깔', 'yánsè'),
    (v_deck, '上', '위, 오르다', 'shàng'),
    (v_deck, '花园', '정원', 'huāyuán'),
    (v_deck, '小区', '주택 단지', 'xiǎoqū'),
    (v_deck, '便利店', '편의점', 'biànlìdiàn'),
    (v_deck, '先生', '미스터, ~씨', 'xiānsheng'),
    (v_deck, '大门', '정문, 대문', 'dàmén'),
    (v_deck, '安全', '안전하다', 'ānquán'),
    (v_deck, '外', '밖, 외부', 'wài'),
    (v_deck, '一共', '모두, 합해서', 'yígòng');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 27 간접 목적어 사용하기', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '意大利语', '이탈리아어', 'Yìdàlìyǔ'),
    (v_deck, '小组', '팀, 그룹', 'xiǎozǔ'),
    (v_deck, '作文', '작문', 'zuòwén'),
    (v_deck, '问题', '질문, 문제', 'wèntí'),
    (v_deck, '节', '교시(수업 단위)', 'jié'),
    (v_deck, '选', '고르다, 선택하다', 'xuǎn'),
    (v_deck, '问', '묻다, 질문하다', 'wèn'),
    (v_deck, '讨论', '토론하다, 논의하다', 'tǎolùn'),
    (v_deck, '题目', '제목, 문제', 'tímù'),
    (v_deck, '什么时候', '언제', 'shénme shíhou'),
    (v_deck, '笔', '펜, 필기구', 'bǐ'),
    (v_deck, '支', '자루(펜 등을 세는 양사)', 'zhī'),
    (v_deck, '邮件', '우편물, 이메일', 'yóujian'),
    (v_deck, '封', '통(편지 등을 세는 양사)', 'fēng'),
    (v_deck, '借', '빌리다, 빌려주다', 'jiè'),
    (v_deck, '想法', '생각, 아이디어', 'xiǎngfǎ'),
    (v_deck, '有用', '유용하다, 쓸모가 있다', 'yǒuyòng'),
    (v_deck, '翻译', '번역하다, 통역하다', 'fānyì'),
    (v_deck, '给', '주다, ~에게', 'gěi'),
    (v_deck, '见', '만나다, 보다', 'jiàn'),
    (v_deck, '昨晚', '어젯밤', 'zuówǎn'),
    (v_deck, '交', '제출하다, 내다', 'jiāo'),
    (v_deck, '完成', '완성하다, 마치다', 'wánchéng'),
    (v_deck, '每个', '각각, 모든 것', 'měi gè'),
    (v_deck, '怎么办', '어떻게 하지', 'zěnmebàn');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 28 (내용 정리 중)', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '打车', '택시를 잡다', 'dǎ chē'),
    (v_deck, '北京大学', '베이징대학교', 'Běijīng Dàxué'),
    (v_deck, '最好', '가장 좋다, 제일 좋은 건', 'zuìhǎo'),
    (v_deck, '附近', '근처', 'fùjìn'),
    (v_deck, '离', '~로부터(거리)', 'lí'),
    (v_deck, '街', '거리', 'jiē'),
    (v_deck, '一条街', '한 거리', 'yì tiáo jiē'),
    (v_deck, '推荐', '추천하다', 'tuījiàn'),
    (v_deck, '近', '가깝다', 'jìn'),
    (v_deck, '米', '미터', 'mǐ'),
    (v_deck, '天安门', '톈안먼(천안문)', 'Tiān''ānmén'),
    (v_deck, '差不多', '거의 비슷하다, 대략', 'chàbuduō'),
    (v_deck, '千', '천(1000)', 'qiān'),
    (v_deck, '两千', '2000', 'liǎngqiān'),
    (v_deck, '地图', '지도', 'dìtú'),
    (v_deck, '走', '걷다, 가다', 'zǒu'),
    (v_deck, '怎么走', '어떻게 가요', 'zěnme zǒu'),
    (v_deck, '往', '~쪽으로', 'wǎng'),
    (v_deck, '右', '오른쪽', 'yòu'),
    (v_deck, '市中心', '시내 중심', 'shìzhōngxīn'),
    (v_deck, '不用谢', '천만에요', 'búyòng xiè'),
    (v_deck, '转', '돌다, 회전하다', 'zhuǎn');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 29 스포츠', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '巴黎', '파리', 'Bālí'),
    (v_deck, '奥运会', '올림픽', 'Àoyùnhuì'),
    (v_deck, '打开', '열다, 틀다', 'dǎkāi'),
    (v_deck, '国家', '국가', 'guójiā'),
    (v_deck, '期待', '기대하다', 'qīdài'),
    (v_deck, '凌晨', '새벽', 'língchén'),
    (v_deck, '羽毛球', '배드민턴', 'yǔmáoqiú'),
    (v_deck, '跳水', '다이빙', 'tiàoshuǐ'),
    (v_deck, '精彩', '훌륭하다, 멋지다', 'jīngcǎi'),
    (v_deck, '比赛', '경기, 시합', 'bǐsài'),
    (v_deck, '西班牙', '스페인', 'Xībānyá'),
    (v_deck, '法国', '프랑스', 'Fǎguó'),
    (v_deck, '队', '팀', 'duì'),
    (v_deck, '加油', '힘내라, 파이팅', 'jiāyóu'),
    (v_deck, '为什么', '왜', 'wèishénme'),
    (v_deck, '粉丝', '팬', 'fěnsī'),
    (v_deck, '高', '높다, 키가 크다', 'gāo'),
    (v_deck, '运动员', '운동선수', 'yùndòngyuán'),
    (v_deck, '啤酒', '맥주', 'píjiǔ'),
    (v_deck, '第一名', '1등', 'dì yī míng'),
    (v_deck, '得', '얻다', 'dé'),
    (v_deck, '庆祝', '축하하다', 'qìngzhù'),
    (v_deck, '结束', '끝나다', 'jiéshù');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 30 (내용 정리 중)', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '小偷', '도둑', 'xiǎotōu'),
    (v_deck, '前天', '그제', 'qiántiān'),
    (v_deck, '没事吧', '괜찮아?', 'méishì ba'),
    (v_deck, '进', '들어가다', 'jìn'),
    (v_deck, '小区', '주택단지', 'xiǎoqū'),
    (v_deck, '害怕', '무서워하다', 'hàipà'),
    (v_deck, '报警', '(경찰에) 신고하다', 'bàojǐng'),
    (v_deck, '加班', '야근하다', 'jiābān'),
    (v_deck, '当时', '그 당시', 'dāngshí'),
    (v_deck, '钱', '돈', 'qián'),
    (v_deck, '游戏机', '게임기', 'yóuxìjī'),
    (v_deck, '生气', '화나다', 'shēngqì'),
    (v_deck, '忘', '잊다', 'wàng'),
    (v_deck, '偷', '훔치다', 'tōu'),
    (v_deck, '电梯', '엘리베이터', 'diàntī'),
    (v_deck, '认识', '(사람을) 알다', 'rènshi'),
    (v_deck, '看见', '보다, 보이다', 'kànjiàn'),
    (v_deck, '遛狗', '개를 산책시키다', 'liù gǒu'),
    (v_deck, '灰色', '회색', 'huīsè'),
    (v_deck, '多高', '키가 얼마나', 'duō gāo'),
    (v_deck, '上衣', '상의', 'shàngyī'),
    (v_deck, '一米', '1미터', 'yì mǐ');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 31 (내용 정리 중)', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '眼睛', '눈', 'yǎnjīng'),
    (v_deck, '眼药水', '안약', 'yǎnyàoshuǐ'),
    (v_deck, '干', '마르다, 건조하다', 'gān'),
    (v_deck, '最近', '최근', 'zuìjìn'),
    (v_deck, '头发', '머리카락', 'tóufa'),
    (v_deck, '洗发水', '샴푸', 'xǐfàshuǐ'),
    (v_deck, '欢迎光临', '어서오세요', 'huānyíng guānglín'),
    (v_deck, '您', '당신(존칭)', 'nín'),
    (v_deck, '适合', '어울리다, 적합하다', 'shìhé'),
    (v_deck, '产品', '제품', 'chǎnpǐn'),
    (v_deck, '皮肤', '피부', 'pífū'),
    (v_deck, '痒', '가렵다', 'yǎng'),
    (v_deck, '受欢迎', '인기 있다', 'shòu huānyíng'),
    (v_deck, '对', '맞다', 'duì'),
    (v_deck, '教练', '코치', 'jiàoliàn'),
    (v_deck, '健身', '헬스하다', 'jiànshēn'),
    (v_deck, '每周', '매주', 'měi zhōu'),
    (v_deck, '好吗', '~할래?(제안)', 'hǎo ma'),
    (v_deck, '酸奶', '요거트', 'suānnǎi'),
    (v_deck, '生菜', '상추', 'shēngcài'),
    (v_deck, '身体', '몸, 신체', 'shēntǐ'),
    (v_deck, '以后', '이후에', 'yǐhòu'),
    (v_deck, '甜', '달다', 'tián');

  insert into public.decks (owner_id, name, icon, language) values (v_owner, '섹션2 유닛 32 (내용 정리 중)', '🦉', '중국어') returning id into v_deck;
  insert into public.words (deck_id, front, back, pinyin) values
    (v_deck, '父母', '부모', 'fùmǔ'),
    (v_deck, '毕业典礼', '졸업식', 'bìyè diǎnlǐ'),
    (v_deck, '月', '월, 달', 'yuè'),
    (v_deck, '号', '일(날짜)', 'hào'),
    (v_deck, '会', '~할 것이다, ~할 수 있다', 'huì'),
    (v_deck, '名人', '유명인', 'míngrén'),
    (v_deck, '外婆', '외할머니', 'wàipó'),
    (v_deck, '下雨', '비가 오다', 'xiàyǔ'),
    (v_deck, '除了', '~을 제외하고', 'chúle'),
    (v_deck, '恭喜', '축하해', 'gōngxǐ'),
    (v_deck, '零', '영(0)', 'líng'),
    (v_deck, '毕业证', '졸업증', 'bìyèzhèng'),
    (v_deck, '高跟鞋', '하이힐', 'gāogēnxié'),
    (v_deck, '外公', '외할아버지', 'wàigōng'),
    (v_deck, '面试', '면접', 'miànshì'),
    (v_deck, '工作', '일하다, 일', 'gōngzuò'),
    (v_deck, '搬到', '~로 이사가다', 'bāndào'),
    (v_deck, '开始', '시작하다', 'kāishǐ'),
    (v_deck, '前', '전에, 앞', 'qián'),
    (v_deck, '生物', '생물', 'shēngwù'),
    (v_deck, '专业', '전공', 'zhuānyè'),
    (v_deck, '心理学', '심리학', 'xīnlǐxué'),
    (v_deck, '后', '후에, 뒤', 'hòu'),
    (v_deck, '或者', '또는', 'huòzhě');

end $$;